# Generated by Django 2.1.5 on 2019-03-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190327_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
