# Generated by Django 2.1.5 on 2019-04-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190329_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Accepted'), (2, 'Prepared'), (3, 'Assigned'), (4, 'Pickup'), (5, 'Delivered'), (6, 'Cancelled'), (7, 'Failed')], default=0),
        ),
    ]
